git-test-submit: make error messages more useful
This is what a new error message for a merge conflict will look like.
The "CONFLICT" part is the new part.

error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
CONFLICT (content): Merge conflict in overlay-lakitu/app-emulation/cloud-init-config-lakitu/cloud-init-config-lakitu-1.0.0-r3.ebuild

BUG=chromium:1061504
TEST=locally

Change-Id: I7add0e0ddfc0d75c5b951d8c8299aadec90dfa24
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/infra/recipes/+/2102973
Commit-Queue: Sean Abraham <seanabraham@chromium.org>
Reviewed-by: Michael Mortensen <mmortensen@google.com>
Reviewed-by: Dhanya Ganesh <dhanyaganesh@chromium.org>