code-coverage: Fix bug where path mapping arg is not defined
manual testing:

Before this change running clean_coverage_file command errors out with :

AttributeError: 'Namespace' object has no attribute 'path_mapping_file'

But after the change, I no longer see this error.

BUG=b:232077202
TEST=manual

Change-Id: I034bc64259b676d1c447c17517bdda0924697ea0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/infra/recipes/+/3637387
Auto-Submit: Kshitij Pancholi <panchok@google.com>
Reviewed-by: Hengxiang Hu <hengxianghu@google.com>
Reviewed-by: Alex Bergman <abergman@google.com>
Commit-Queue: Alex Bergman <abergman@google.com>