[recipes] Add a presubmit check that checks if the doc needs regeneration
In order to test this commit, use the patch below to modify labpack/api.py
in such a way tha a change to the markdown file is produced, then observe
the presence of an error message.

Here is the patch that I used to make the doc file out of date without changing
any observable behavior.

```
diff --git a/recipe_modules/labpack/api.py b/recipe_modules/labpack/api.py
index 35640160c6..06ded75e18 100644

Change-Id: Ib2431dbcfd8f9084c91c72639af87cfccdc8044d
--- a/recipe_modules/labpack/api.py
+++ b/recipe_modules/labpack/api.py
@@ -29,7 +29,8 @@ class LabpackCommand(recipe_api.RecipeApi):
     self.cipd_package = properties.version.cipd_package or DEFAULT_CIPD_PACKAGE
     self.downloaded_executable_path = None

-  def has_downloaded_package(self):
+  def has_downloaded_package(self, foo=None):
+    del foo
     return self.downloaded_executable_path is not None  # pragma: nocover

   def get_cipd_executable_name(self):
```

```
Evaluation of CheckChangeOnCommit failed: Command './recipes.py doc --check' returned non-zero exit status 1, Traceback (most recent call last):
  File ".../presubmit_support.py", line 1652, in _run_check_function
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File ".../PRESUBMIT.py", line 106, in CommitChecks
    DocCheck(input_api, output_api)
  File ".../PRESUBMIT.py", line 82, in DocCheck
    input_api.subprocess.check_call(cmd)
  File ".../subprocess2.py", line 227, in check_call
    check_call_out(args, **kwargs)
  File ".../subprocess2.py", line 220, in check_call_out
    raise CalledProcessError(
subprocess2.CalledProcessError: Command './recipes.py doc --check' returned non-zero exit status 1
```

Change-Id: Ib5fca5d7259012b7df039b9b90f8594832b281ea
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/infra/recipes/+/4575982
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Reviewed-by: Greg Edelston <gredelston@google.com>
Reviewed-by: Yuanjun Huang <yuanjunh@google.com>
Commit-Queue: Gregory Nisbet <gregorynisbet@google.com>