code_coverage: Fix shutil.copyfile error
shutil.copyfile expects filenames, not file objects.

```
Traceback (most recent call last):
  File "/home/jbettis/chromiumos/infra/recipes/recipe_modules/code_coverage/resources/clean_coverage_file.py", line 90, in <module>
    sys.exit(main())
  File "/home/jbettis/chromiumos/infra/recipes/recipe_modules/code_coverage/resources/clean_coverage_file.py", line 83, in main
    clean_file_paths(params.coverage_file, params.constants_file,
  File "/home/jbettis/chromiumos/infra/recipes/recipe_modules/code_coverage/resources/clean_coverage_file.py", line 35, in clean_file_paths
    shutil.copyfile(coverage_file, output_file)
  File "/home/jbettis/.vpython-root/86f5fc/lib/python3.8/shutil.py", line 243, in copyfile
    if _samefile(src, dst):
  File "/home/jbettis/.vpython-root/86f5fc/lib/python3.8/shutil.py", line 220, in _samefile
    return os.path.samefile(src, dst)
  File "/home/jbettis/.vpython-root/86f5fc/lib/python3.8/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper
```

BUG=b:231639771
TEST=vpython3 \
~/chromiumos/infra/recipes/recipe_modules/code_coverage/resources/clean_coverage_file.py \
--coverage-file build/zephyr/fullpaths.info \
--constants-file ~/chromiumos/infra/recipes/recipe_modules/code_coverage/resources/path_mapping.json \
--output-file /tmp/cleaned.file --to_absolute_path False

Change-Id: If0f8c6ed7974f1a4ab3e08a09bc4f98b55ad488a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/infra/recipes/+/3683584
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Chris Gerber <gerb@google.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Chris Gerber <gerb@google.com>